name: build-em-dosbox
on: [push]
jobs:
    runs-on: ubuntu-latest
    steps:
        - name: Install GNU Autotools
        - run: sudo apt-get install autotools-dev autoconf automake
        - name: Install Emscripten [latest]
        - uses: mymindstorm/setup-emsdk@v6
        - name: Checkout repository
        - uses: actions/checkout@v2
        - name: Using compile time flags
        - run: echo "emconfigure ./configure --enable-wasm --disable-opengl"
        - name: Configure and Build
        - run: |
            cd em-dosbox
            ./autogen.sh
            emconfigure ./configure --enable-wasm --disable-opengl
            emmake make
